In [1]:
import numpy as np

In [3]:
my_list=[0,1,2,10,20,50]

In [4]:
array=np.array(my_list)

In [5]:
array

array([ 0,  1,  2, 10, 20, 50])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [11]:
np.arange(0,10,(2,3))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [22]:
np.random.randint(0,10,(3,5))

array([[2, 4, 4, 2, 7],
       [8, 2, 2, 6, 5],
       [3, 0, 7, 3, 4]])

In [23]:
np.random.seed(10)

In [24]:
arr=np.random.randint(0,100,10)

In [25]:
arr

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

In [26]:
arr1=arr

In [27]:
arr1

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

In [28]:
arr.max()

93

In [29]:
arr.min()

0

In [32]:
arr.sum()

408

In [33]:
arr.mean()

40.8

In [40]:
arr.reshape(5,2)

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

In [42]:
mat=np.arange(0,100).reshape(10,10)

In [43]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat[4,2]

42

In [54]:
mat[4:,4:]

array([[44, 45, 46, 47, 48, 49],
       [54, 55, 56, 57, 58, 59],
       [64, 65, 66, 67, 68, 69],
       [74, 75, 76, 77, 78, 79],
       [84, 85, 86, 87, 88, 89],
       [94, 95, 96, 97, 98, 99]])

In [55]:
a=mat>50

In [58]:
b=mat[a]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [62]:
c=mat[~a]

In [63]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])